/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://l7xcz4jnlrcarht7aeuz3ykpwa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-2:1562a812-c5dd-43e3-a5e2-2504cd15edd9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ssjtgUGQ9",
    "aws_user_pools_web_client_id": "2fq6b3b6hefp5vfg84t6n5a8l3",
    "oauth": {
        "domain": "vinotest3e756ba5-3e756ba5-apps.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://apps.d3p9tw1olyeelo.amplifyapp.com/",
        "redirectSignOut": "https://apps.d3p9tw1olyeelo.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
